version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: webshell
    ports:
      tools-webide-vscode: 6800
      tools-ssh: 6822
      apps-application: 6860
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
  services:
    webshell:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-node-v2-vscode
      restart: always
      environment:
        LOCAL_USER_PASSWORD: root123
      volumes:
        - .:/home/project
        - /var/run/docker.sock:/var/run/docker.sock
        - C:\Users\Administrator\.kube\config:/home/smartide/.kube/config
      ports:
        - 6822:22
        - 6800:3000
        - 6860:6860
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true